#!/usr/bin/env bash

echo "Starting Puppet bootstrap process..."

# Check that puppet isn't already installed
if [ -d /etc/puppet ]; then
    echo "Puppet already installed - not reinstalling"
    exit
fi

# Install puppetlabs repo and puppet package
echo "Installing puppet..."
sudo rpm -ivh https://yum.puppetlabs.com/el/6/products/x86_64/puppetlabs-release-6-7.noarch.rpm
yum install -y puppet 

# Install puppetlabs-mysql module
# https://forge.puppetlabs.com/puppetlabs/mysql
puppet module install puppetlabs-mysql
