#!/usr/bin/env bash

# Import example-data.sql into an existing SQL database
# May be run multiple times, so shouldn't overwrite if data already exists

USER=$1      # User to insert data with - probably root
ROOTPW=$2    # MySQL $USER password
DATABASE=$3  # database to restore $SQL_FILE into
SQL_FILE=$4  # file in which SQL data is stored - eg /vagrant/vagrant-config/mysql/example-data.sql
#echo "Variables are $1 $2 $3 $4"

touchfile="/etc/mysql/vagrant-created-db" # file used to determine if this script has already run

if [ -e $touchfile ]; then
    echo "Tables have already been created, so stopping"
    echo "(Touchfile $touchfile exists)"
    exit;
fi

echo "Rebuilding tables from $SQL_FILE"
mysql -u $USER -p$ROOTPW $DATABASE < $SQL_FILE

touch $touchfile
